version: "3.7"

services:
  database:
    build: .
    container_name: database
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Un!q@to2023
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
  
  myapp:
    build: ./php/.  
    container_name: myapp
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    

