# Use the official Microsoft SQL Server 2019 image as base image
FROM mcr.microsoft.com/mssql/server:2019-latest

# Set environment variables
ENV ACCEPT_EULA=Y
ENV pass=Un!q@to2023
ENV db=db_vero_digital
ENV user=sa 
ENV host=localhost

# Expose the port
EXPOSE 1433

# Start MSSQL service
CMD ["/opt/mssql/bin/sqlservr"]