version: '3.8'
services:
  mssql-server:
    build:
      context: .
      dockerfile: Dockerfile-mssql
    # ports:
    # - "1433:1433"
    networks:
      - test

  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mssql-server
    networks:
      - test

networks:
  test: